name: Cypress Tests
'on':
  - push
  #schedule:
   #- cron: "*/5 * * * *"
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
        
      - name: Cypress info
        uses: cypress-io/github-action@v2
        with:
          build: npm run test
          continue-on-error: true
      
      - name: upload Test Results
        uses: actions/upload-artifact@v2
        with: 
         name: functional-test-result
         path: CddrReport.html
         
      - name: test2     
        uses: actions/upload-artifact@v2
        with: 
          name: functional-test-result
          path: CddrReport.json
  
