name: Cypress Tests
'on':
  - push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
        
      - name: Cypress info
        uses: cypress-io/github-action@v2
        with:
          build: npm run test
          
  
