name: Cypress Tests For Demo
on:
 push:
  branches: [master]
     
jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
     contents: read
     packages: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build with NPM
        run: npm run test
   
        
