# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Build_and_Push:
   runs-on: ubuntu-latest
   permissions:
    contents: read
    packages: write
   env:
    USER: ${{ secrets.DOCKERHUB_USERNAME }}
    PASS: ${{ secrets.DOCKERHUB_TOKEN }}
   steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Docker Login
      run:  docker login -u $USER -p $PASS mckinseydemoproject.jfrog.io
    - name: Image Build
      run: |
       docker push mckinsey-getstarted-docker.jfrog.io/Cypress-Github-Actions
    - name: Docker Logout
      run:  Docker logout mckinseydemoproject.jfrog.io
      
  
      
